### ISSUE TITLE
[FEATURE]newline in a table cell

### ISSUE THREAD

**Issue by tiennv597** [the-airbender/quill_html_editor#118]
i am trying to write multiple lines of text in 1 cell, however it seems that is not possible at the moment.
I'm hoping there's a way I can actively split it into a newline. i tried adding </br> but it doesn't seem to work.

Current status:
![image](https://github.com/the-airbender/quill_html_editor/assets/58663057/5d45f5c5-26cc-42dc-80c5-78a88878113e)

I hope:
![image](https://github.com/the-airbender/quill_html_editor/assets/58663057/8679aa3a-9c33-46bf-87da-7c4315d20f47)

Thank you with all my heart. You've executed an outstanding project @the-airbender

**Comment by the-airbender** [comment]
Hi @tiennv597 ,

Thank you for your kind words! I appreciate your support.

Regarding your concern, it appears that you're encountering a limitation in the table feature of Quill.js. As of now, it's not possible to have multiple lines of text within a single cell using Quill.js tables.

I'm aware that there is an open issue related to this on Quill.js's GitHub repository. While there isn't a straightforward solution at the moment, will look for a workaround. Closing this issue for now due to limitation. However, I will post if I find any workarounds or updates regarding the same. 

Please feel free to reopen or add your comments here. 

Thanks :)
