### ISSUE TITLE
Editor autofocus property 

### ISSUE THREAD

**Issue by steveneal** [the-airbender/quill_html_editor#24]
Would it be possible to include an autofocus property?

My use case is to allow users to edit snippets of text and it would be more intuituve if the keyboard appeared immediately.

I'm just starting to use this plugin and loving it - so much better that the alternatives. 

Thanks for your time putitng this together!

**Comment by the-airbender** [comment]
Thank you for you feedback @steveneal  :)

Will try to add this in coming release.

Thanks!

**Comment by steveneal** [comment]
Thank you.... if it's an easy addition to be able to control focus, or at least be able to dismiss the keybaord when required, that would be great too.

**Comment by the-airbender** [comment]
Hi @steveneal,

I have added `requestFocus` and `unFocus` methods to the editor. 

Unfortunately, due to limitations of webview in flutter, the focus in editor will not open the soft keyboard. Hoping this will be available in future. 

However, `controller.unFocus()` will dismiss the keyboard, hope this helps.  These methods are available in [ver 2.0.9](https://pub.dev/packages/quill_html_editor/versions/2.0.9)

Thanks!
