### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by vishalm29** [the-airbender/quill_html_editor#44]
Great assistance with this bundle, to start with.
I have one request: please include a function that prevents keyboard input when editing rather than typing. It will be really beneficial.
Said that the keyboard was closed when in editing mode.
And one more thing: Can we add a custom toolbar option for text selection that returns both html and plain text?

**Comment by the-airbender** [comment]
Hi @vishalm29 ,

Thank you for you feedback!

Regarding the 1st point, we can only close the keyboard by unfocusing the editor, since, in edit mode, we will deal with the selection or tap on text which will get back the focus ( which opens the keyboard), there will be an ambiguity in some cases, which might cause an unexpected behaviour.

Regarding the 2nd Point, could you please give more information on  
> toolbar option for text selection that returns both html and plain text?


PS: We already have a method `controller.getSelectedText()` , which returns the selected text in `plain` text format. However, I will also add an additional method to get the `html` text of selection. 

Please let me know if you are referring to the same.

Thanks :)

**Comment by the-airbender** [comment]
Hi @vishalm29 

I have added a method `controller. getSelectedHtmlText()` to get the selected text in `html` format. Please check it out in the latest version ver [2.1.7](https://pub.dev/packages/quill_html_editor/versions/2.1.7)

Thanks!

**Comment by vishalm29** [comment]
Hi @the-airbender 
I appreciate all of your assistance.
