### ISSUE TITLE
i can't able to select bold or italic after entering any text and clearing the text [BUG]

### ISSUE THREAD

**Issue by shootlens** [the-airbender/quill_html_editor#72]
let's say i have entered some text and again i have cleared that text without sending, now i can't able to select unselect the styles ITALIC or BOLD.

**Comment by the-airbender** [comment]
Hi @shootlens,

Thank you for reporting the bug.
To understand it better could you please help me with the following. I appreciate if you could share the screen recording. 

---

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Flutter Doctor**
Please run `flutter doctor` in the terminal and add the  log here.

**Additional context**
Add any other context about the problem here.

Thanks :)

**Comment by the-airbender** [comment]
Hello @shootlens ,
This issue is fixed in the new release. I have tested it on Android 12 and on iOS 16.  Please check it out, feel free to reopen the issue, if you still face any issues.

Thanks :)
