### ISSUE TITLE
can't able to select the edit options [BUG]

### ISSUE THREAD

**Issue by shootlens** [the-airbender/quill_html_editor#73]
i have entered some text, let's say an example 

example: "Hello this is my text[i want to add some text with bold or italic without giving space after Text word]" i can't able to do.  But i can able to edit after giving space after the word.

**Comment by the-airbender** [comment]
Hi @shootlens,

Thank you for reporting the bug.
To understand it better could you please help me with the following. I appreciate if you could share the screen recording. 

---

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Flutter Doctor**
Please run `flutter doctor` in the terminal and add the  log here.

**Additional context**
Add any other context about the problem here.

Thanks :)

**Comment by the-airbender** [comment]
Hello @shootlens,

I am closing this issue, please feel free to reopen if you still see any issues. 

Thanks :)
