### ISSUE TITLE
[BUG] Focus problem (unnecessary autofocus) on field in flutter web

### ISSUE THREAD

**Issue by bambinoua** [the-airbender/quill_html_editor#81]
I use the `QuillHTmlEditor` as the last field on my form which does not focus on any other field. On dialog open your widget become focusable. It is wise to use `FocusNode` for the widget.

**Comment by the-airbender** [comment]
Hello @bambinoua ,

Sorry for the late response.

Could you please help me with some minimal reproducible code to understand this better?

I appreciate if you can also attach a few screenshots if possible.

Thanks :)

**Comment by bambinoua** [comment]
@the-airbender unfortunately I cannot do this because of stopping use your package due to functionality lacks of our requirements.

**Comment by the-airbender** [comment]
Hi @bambinoua,

Thank you for you response. 
If the problem is similar to #83,  I have suggested a solution in that issue. Please check it out. If it is something else, feel free to reopen this issue. 

Thanks :)

**Comment by Avo-Mandjian** [comment]
Hello @the-airbender ,

The problem is not similar to #83 

try adding a listview, add some containers to its children(make sure it is larger than screen height) and add QuillHtmlEditor at the end of the children, you'll see that the QuillHtmlEditor has autofocus by default and it'll scroll down the page at the QuillHtmlEditor position.

expected behaviour:
we should be able to have autofocus true/false so that it won't focus and scroll to QuillHtmlEditor automatically

thank you for this great package
